### ISSUE TITLE
In viewNotifications, 'kind' parameter is required?

### ISSUE THREAD

**Issue by quocanhtran1502** [kvandake/onesignal#22]
I read in documentation, 'kind' has 3 types to return. But default if we don't declare 'kind', it will return all 3 types. But in onesignal-api-client-core, 'kind' is required. Can you make it optional, so that we can basicly return all notifications instead of making 3 different functions to get 3 different 'kinds', then combine them?

P/s: Sorry if my English bad, it's not my mother language

**Comment by panalgin** [comment]
hello,

it's better to use onesignal's own node js api, this library is well outdated and onesignal has changed their API's

**Comment by quocanhtran1502** [comment]
Thanks for reply. I'm now working in TS project (NestJS), so if i use nodeJS api, it will show a lot of error and warning. And i don't want that. For now, i'm using you library and it still working.
Btw, if you are no longer developing this project, I will find another way to figure it out. Thank you!

**Comment by panalgin** [comment]
Hello, there must be another issue in your case because I'm using onesginal's official nodejs sdk as well with nestjs and do not have errors at the moment. This library is outdated like more than 1 year and has a lot of missing features, probably soon will not work due to onesignal's deprecation of old api. 

It is logical to use onesignal's nodejs sdk if you are about to start a project. In the long term you will have issues with this library

Thank you
